file:
    staticAccessPath: /upload/**
server:
    port: 8800
mybatis:
    mapper-locations: classpath:mapper/*.xml
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/social?useSSL=false&serverTimezone=UTC
        username: root
        password: admin
    resources:
        chain:
            strategy:
                content:
                    enabled: true
                    paths: //**,/upload/**
        add-mappings: true
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 5MB
            max-request-size: 20MB
    mail:
        host: smtp.qq.com
        username: kk996icu@qq.com
        password: rewwyvbraogwcjfh
        default-encoding: UTF-8
    redis:
        lettuce:
            pool:
                max-wait: 60s
                max-idle: 10
                min-idle: 10
                max-activ: 8
        timeout: 1000
        database: 2
        host: 127.0.0.1
        port: 6379
        password:
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql