file:
    staticAccessPath: /upload/**
server:
    port: 8800
spring:
    resources:
        chain:
            strategy:
                content:
                    enabled: true
                    paths: //**,/upload/**
        add-mappings: true
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 5MB
            max-request-size: 10MB
    mail:
        host: smtp.qq.com
        username: kk996icu@qq.com
        password: rewwyvbraogwcjfh
        default-encoding: UTF-8
    redis:
        jedis:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
        lettuce:
            pool:
                min-idle: 0
        timeout: 1000
        database: 2
        host: 127.0.0.1
        password: admin
        port: 6379
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql