file:
    staticAccessPath: /upload/**
server:
    port: 8800
spring:
    resources:
        chain:
            strategy:
                content:
                    enabled: true
                    paths: /dist/**,/upload/**
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 5MB
            max-request-size: 10MB
    mail:
        host: smtp.163.com
        username: kk996icu@163.com
        password: QPOMJPQSTBSXKODQ
        default-encoding: UTF-8
